backend:
  name: github
  repo: NikitaVr/dndcrafting
media_folder: static/img
public_folder: /img

collections:
  - label: "Ingredients"
    name: "ingredients"
    folder: content/ingredients
    create: true
    fields:
      - {
          label: "Collection",
          name: "collection",
          widget: "hidden",
          default: "ingredients",
        }
      - { name: name, label: Name }
      - { name: type, label: Type }
      - { label: Image, name: image, widget: image }

  - label: "Recipe"
    name: "recipe"
    folder: content/recipes
    create: true
    fields:
      - {
          label: "Collection",
          name: "collection",
          widget: "hidden",
          default: "recipes",
        }
      - { name: name, label: Name }
      - label: "Effects"
        name: "effects"
        widget: "list"
        field: { label: Effect, name: effect }
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        field:
          {
            label: Ingredient,
            name: ingredient,
            widget: relation,
            collection: ingredients,
            searchFields: [name, type],
            valueField: name,
            displayFields: [name],
          }
      - { label: Image, name: image, widget: image }
